import { type AgentDecision, type AgentPlaybook } from "@/lib/api";

export function AgentRunView({ playbooks, decisions }: { playbooks: AgentPlaybook[]; decisions: AgentDecision[] }) {
  const latest = decisions[0];
  return <div className="flex flex-col gap-4">
    <section className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-4"><p className="text-[11px] uppercase tracking-wide text-neutral-600">Плейбуки</p><p className="mt-1 text-2xl tabular-nums text-neutral-200">{playbooks.length}</p><p className="mt-1 text-xs text-neutral-500">Критерии, по которым агенты работают.</p></div><div className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-4"><p className="text-[11px] uppercase tracking-wide text-neutral-600">Решения</p><p className="mt-1 text-2xl tabular-nums text-neutral-200">{decisions.length}</p><p className="mt-1 text-xs text-neutral-500">Каждое ждёт отдельного review.</p></div><div className="rounded-xl border border-sky-500/20 bg-sky-500/5 p-4"><p className="text-[11px] uppercase tracking-wide text-sky-300/70">Принцип</p><p className="mt-1 text-sm text-sky-100">Агент предлагает, человек подтверждает.</p><p className="mt-1 text-xs text-sky-200/60">Без автоматического изменения цены.</p></div></section>
    <section className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-4 sm:p-5"><h2 className="text-base font-medium">Как читать запуск</h2><ol className="mt-3 grid gap-2 text-xs text-neutral-400 sm:grid-cols-4">{[["Вход", "Плейбук, продавец, поиски и снимок данных"], ["Анализ", "Отдельные агенты смотрят свои категории"], ["Консенсус", "Сравниваем предложения и конфликты"], ["Review", "Решение по каждому SKU отдельно"]].map(([title, text], index) => <li key={title} className="rounded-lg border border-neutral-800 bg-neutral-950/40 p-3"><span className="text-sky-300">0{index + 1}</span><p className="mt-1 text-neutral-200">{title}</p><p className="mt-1 text-neutral-600">{text}</p></li>)}</ol></section>
    {latest ? <section className="rounded-xl border border-sky-500/25 bg-sky-500/5 p-4 sm:p-5"><p className="text-xs uppercase tracking-wider text-sky-300/70">Последний консенсус</p><h2 className="mt-2 text-lg text-neutral-100">{latest.payload.headline ?? "План ждёт проверки"}</h2><p className="mt-2 text-xs text-neutral-500">Агенты: {(latest.payload.agents ?? []).join(", ") || "не указаны"} · статус: {latest.status}</p><div className="mt-3 flex flex-wrap gap-2">{(latest.payload.items ?? []).slice(0, 6).map((item) => <span key={item.sku} className="rounded-lg border border-neutral-700 bg-neutral-950/40 px-2.5 py-1.5 text-xs text-neutral-300">{item.sku}: {item.current_price.toFixed(0)} → {item.suggested_price.toFixed(0)} ₽</span>)}</div></section> : <section className="rounded-xl border border-dashed border-neutral-800 p-6 text-sm text-neutral-500">Запусков ещё нет. Создайте плейбук и запустите агента, чтобы получить первый отчёт.</section>}
  </div>;
}
