export type Region = { slug: string; name: string };

// Слаг — как в URL Авито (/moskva?q=...). Список основных городов для выбора.
export const REGIONS: Region[] = [
  { slug: "moskva", name: "Москва" },
  { slug: "sankt-peterburg", name: "Санкт-Петербург" },
  { slug: "novosibirsk", name: "Новосибирск" },
  { slug: "ekaterinburg", name: "Екатеринбург" },
  { slug: "kazan", name: "Казань" },
  { slug: "nizhniy_novgorod", name: "Нижний Новгород" },
  { slug: "chelyabinsk", name: "Челябинск" },
  { slug: "samara", name: "Самара" },
  { slug: "omsk", name: "Омск" },
  { slug: "rostov-na-donu", name: "Ростов-на-Дону" },
  { slug: "ufa", name: "Уфа" },
  { slug: "krasnoyarsk", name: "Красноярск" },
  { slug: "voronezh", name: "Воронеж" },
  { slug: "perm", name: "Пермь" },
  { slug: "volgograd", name: "Волгоград" },
  { slug: "krasnodar", name: "Краснодар" },
  { slug: "saratov", name: "Саратов" },
  { slug: "tyumen", name: "Тюмень" },
  { slug: "tolyatti", name: "Тольятти" },
  { slug: "izhevsk", name: "Ижевск" },
  { slug: "barnaul", name: "Барнаул" },
  { slug: "ulyanovsk", name: "Ульяновск" },
  { slug: "irkutsk", name: "Иркутск" },
  { slug: "khabarovsk", name: "Хабаровск" },
  { slug: "yaroslavl", name: "Ярославль" },
  { slug: "vladivostok", name: "Владивосток" },
  { slug: "makhachkala", name: "Махачкала" },
  { slug: "tomsk", name: "Томск" },
  { slug: "orenburg", name: "Оренбург" },
  { slug: "kemerovo", name: "Кемерово" },
  { slug: "novokuznetsk", name: "Новокузнецк" },
  { slug: "ryazan", name: "Рязань" },
  { slug: "naberezhnye_chelny", name: "Набережные Челны" },
  { slug: "astrakhan", name: "Астрахань" },
  { slug: "penza", name: "Пенза" },
  { slug: "lipetsk", name: "Липецк" },
  { slug: "kirov", name: "Киров" },
  { slug: "cheboksary", name: "Чебоксары" },
  { slug: "balashikha", name: "Балашиха" },
  { slug: "kaliningrad", name: "Калининград" },
  { slug: "tula", name: "Тула" },
  { slug: "kursk", name: "Курск" },
  { slug: "sochi", name: "Сочи" },
  { slug: "stavropol", name: "Ставрополь" },
  { slug: "ulan-ude", name: "Улан-Удэ" },
  { slug: "tver", name: "Тверь" },
  { slug: "magnitogorsk", name: "Магнитогорск" },
  { slug: "ivanovo", name: "Иваново" },
  { slug: "bryansk", name: "Брянск" },
  { slug: "belgorod", name: "Белгород" },
  { slug: "surgut", name: "Сургут" },
  { slug: "vladimir", name: "Владимир" },
  { slug: "nizhniy_tagil", name: "Нижний Тагил" },
  { slug: "arkhangelsk", name: "Архангельск" },
  { slug: "chita", name: "Чита" },
  { slug: "smolensk", name: "Смоленск" },
  { slug: "kaluga", name: "Калуга" },
  { slug: "cherepovets", name: "Череповец" },
  { slug: "saransk", name: "Саранск" },
  { slug: "vologda", name: "Вологда" },
  { slug: "yakutsk", name: "Якутск" },
  { slug: "murmansk", name: "Мурманск" },
  { slug: "tambov", name: "Тамбов" },
  { slug: "petrozavodsk", name: "Петрозаводск" },
  { slug: "grozny", name: "Грозный" },
  { slug: "kostroma", name: "Кострома" },
  { slug: "novorossiysk", name: "Новороссийск" },
  { slug: "nizhnevartovsk", name: "Нижневартовск" },
  { slug: "yoshkar-ola", name: "Йошкар-Ола" },
  { slug: "oryol", name: "Орёл" },
  { slug: "sevastopol", name: "Севастополь" },
  { slug: "simferopol", name: "Симферополь" },
];

const REGION_NAMES = new Map(REGIONS.map((region) => [region.slug, region.name]));

export function regionName(slug: string | null | undefined): string {
  if (!slug) {
    return "все города";
  }
  return REGION_NAMES.get(slug) ?? slug;
}
